name: Automated Release

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.github/*'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        ### if: startsWith(github.ref, 'refs/tags/')
        with:
          # files: Release.txt
          tag_name: '1.0.18'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
