name: Automated Release
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.github/*'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        ### if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: 1.0.27
          body: |-
            '## softcommerce/automatic-workflow-test [1.0.27]
            - **Feature**: New feature test
            - **Fix**: A fix for xxx'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
