name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.33 [CE|EE|ECE 2.4.0-2.4.7] 21 Mar 2024
          tag_name: 1.0.33
          body: |-
            ### softcommerce/automatic-workflow-test [1.0.33]
            - **Feature**: New feature test
            - **Fix**: A fix for xxx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
