name: Automated Release
on:
  push:
    branches:
      - "main"
      - "master"
    paths-ignore:
      - '.github/*'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 1.0.31
          body: |-
            ### softcommerce/automatic-workflow-test [1.0.31]
            - **Feature**: New feature test
            - **Fix**: A fix for xxx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
