name: Release

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: changes
        run: |
          # Get last tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          if [ -z "$LAST_TAG" ]; then
            echo "No previous tags found"
            COMMITS=$(git log --oneline -10)
          else
            echo "Last tag: $LAST_TAG"
            COMMITS=$(git log ${LAST_TAG}..HEAD --oneline)
          fi
          
          if [ -z "$COMMITS" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Commits since last release:"
            echo "$COMMITS"
          fi

      - name: Determine version bump
        if: steps.changes.outputs.has_changes == 'true'
        id: version
        run: |
          # Get current version from composer.json
          CURRENT_VERSION=$(jq -r '.version // "0.0.0"' composer.json)
          echo "Current version: $CURRENT_VERSION"
          
          # Analyze commits
          VERSION_TYPE="patch"
          
          # Get commits since last tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            COMMITS=$(git log --pretty=format:"%s" -10)
          else
            COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"%s")
          fi
          
          # Check for version indicators
          if echo "$COMMITS" | grep -qE "(BREAKING CHANGE|!:)"; then
            VERSION_TYPE="major"
          elif echo "$COMMITS" | grep -qE "^feat(\(.*\))?:"; then
            VERSION_TYPE="minor"
          fi
          
          echo "Version type: $VERSION_TYPE"
          
          # Calculate new version
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          
          case $VERSION_TYPE in
            major)
              NEW_VERSION="$((MAJOR + 1)).0.0"
              ;;
            minor)
              NEW_VERSION="${MAJOR}.$((MINOR + 1)).0"
              ;;
            patch)
              NEW_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))"
              ;;
          esac
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "version_type=$VERSION_TYPE" >> $GITHUB_OUTPUT

      - name: Update version
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          # Update composer.json
          jq --arg version "${{ steps.version.outputs.new_version }}" \
            '.version = $version' composer.json > composer.tmp && \
            mv composer.tmp composer.json
          
          # Configure git
          git config --global user.email "ci@softcommerce.com"
          git config --global user.name "SoftCommerce CI"
          
          # Commit version change
          git add composer.json
          git commit -m "chore(release): ${{ steps.version.outputs.new_version }}"

      - name: Create release
        if: steps.changes.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_NAME: ${{ github.repository }}
        run: |
          VERSION="${{ steps.version.outputs.new_version }}"
          
          # Create and push tag
          git tag -a "v${VERSION}" -m "Release v${VERSION}"
          git push origin main --follow-tags
          
          # Generate changelog
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            CHANGELOG=$(git log --pretty=format:"- %s" -10)
          else
            CHANGELOG=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s")
          fi
          
          # Create GitHub release
          gh release create "v${VERSION}" \
            --title "v${VERSION}" \
            --notes "## Changes\n\n${CHANGELOG}\n\n---\n\n**Full Changelog**: https://github.com/${{ github.repository }}/compare/${LAST_TAG}...v${VERSION}"